// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {time} from '../models';

export function CambiarPasswordDocente(arg1:number,arg2:string):Promise<void>;

export function CerrarSesion():Promise<void>;

export function CrearDocente(arg1:string,arg2:string):Promise<void>;

export function EliminarDocente(arg1:number):Promise<void>;

export function FinalizarLogin():Promise<void>;

export function FinalizarPrestamo(arg1:number):Promise<void>;

export function ListarDocentes():Promise<Array<db.Usuario>>;

export function ListarEstudiantes():Promise<Array<db.Solicitante>>;

export function Login(arg1:string,arg2:string):Promise<db.Usuario>;

export function ObtenerAsignaturas():Promise<Array<db.Asignatura>>;

export function ObtenerGradosPorNivel(arg1:number):Promise<Array<db.Grado>>;

export function ObtenerLibros():Promise<Array<db.Libro>>;

export function ObtenerNiveles():Promise<Array<db.NivelAcademico>>;

export function ObtenerNivelesConGrados():Promise<Array<db.NivelAcademico>>;

export function ObtenerPrestamos():Promise<Array<db.Prestamo>>;

export function ObtenerSesionActual():Promise<db.Usuario>;

export function RegistrarLibro(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function RegistrarPrestamo(arg1:db.Solicitante,arg2:number,arg3:number,arg4:time.Time):Promise<void>;
