// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CambiarPasswordDocente(arg1, arg2) {
  return window['go']['main']['App']['CambiarPasswordDocente'](arg1, arg2);
}

export function CerrarSesion() {
  return window['go']['main']['App']['CerrarSesion']();
}

export function CheakAdminExists() {
  return window['go']['main']['App']['CheakAdminExists']();
}

export function CrearDocente(arg1, arg2) {
  return window['go']['main']['App']['CrearDocente'](arg1, arg2);
}

export function CreatefirstAdmin(arg1, arg2) {
  return window['go']['main']['App']['CreatefirstAdmin'](arg1, arg2);
}

export function EliminarDocente(arg1) {
  return window['go']['main']['App']['EliminarDocente'](arg1);
}

export function FinalizarLogin() {
  return window['go']['main']['App']['FinalizarLogin']();
}

export function FinalizarPrestamo(arg1) {
  return window['go']['main']['App']['FinalizarPrestamo'](arg1);
}

export function ListarDocentes() {
  return window['go']['main']['App']['ListarDocentes']();
}

export function ListarEstudiantes() {
  return window['go']['main']['App']['ListarEstudiantes']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function ObtenerAsignaturas() {
  return window['go']['main']['App']['ObtenerAsignaturas']();
}

export function ObtenerGradosPorNivel(arg1) {
  return window['go']['main']['App']['ObtenerGradosPorNivel'](arg1);
}

export function ObtenerLibros() {
  return window['go']['main']['App']['ObtenerLibros']();
}

export function ObtenerNiveles() {
  return window['go']['main']['App']['ObtenerNiveles']();
}

export function ObtenerNivelesConGrados() {
  return window['go']['main']['App']['ObtenerNivelesConGrados']();
}

export function ObtenerPrestamos() {
  return window['go']['main']['App']['ObtenerPrestamos']();
}

export function ObtenerSesionActual() {
  return window['go']['main']['App']['ObtenerSesionActual']();
}

export function RegistrarLibro(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegistrarLibro'](arg1, arg2, arg3, arg4);
}

export function RegistrarPrestamo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegistrarPrestamo'](arg1, arg2, arg3, arg4);
}
